### ISSUE TITLE
Usage with Logback Configuration file (logback.xml)

### ISSUE THREAD

**Issue by jaydez** [trautonen/logback-ext#1]
Hi!

Thanks for writing this tool, it provides a very useful link between logback and AWS. I've been trying to integrate it with logback in my current application, and I am wondering whether you had ever used the SQS Appender through the logback configuration file. When I configure my application using the following xml:

```
<configuration scan="true">
    <contextName>myAppName</contextName>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} %contextName [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>
    <appender name="SQS" class="org.eluder.logback.ext.sqs.appender.AsyncSqsAppender">
        <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
            <evaluator class="ch.qos.logback.classic.boolex.OnMarkerEvaluator">
                <marker>myMarker</marker>
            </evaluator>
            <onMismatch>DENY</onMismatch>
            <onMatch>NEUTRAL</onMatch>
        </filter>
        <accessKey>myAccessKey</accessKey>
        <secretKey>mySecretKey</secretKey>
        <queueUrl>http://myurl/</queueUrl>
        <encoder class="org.eluder.logback.ext.jackson.JacksonEncoder">
            <timeStampFormat>yyy-MM-dd'T'HH:mm:ss</timeStampFormat>
        </encoder>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>%d %contextName [%thread] %level %logger - %m%n</Pattern>
        </layout>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="SQS" />
    </root>
</configuration>
```

I get an error when initializing the SqsAppender class:
```
LOGBACK: No context given for org.eluder.logback.ext.sqs.appender.AsyncSqsAppender[null]
00:25:00,478 |-INFO in ch.qos.logback.classic.LoggerContext[myAppName] - Could NOT find resource [logback.groovy]
00:25:00,478 |-INFO in ch.qos.logback.classic.LoggerContext[myAppName] - Could NOT find resource [logback-test.xml]
00:25:00,478 |-INFO in ch.qos.logback.classic.LoggerContext[myAppName] - Found resource [logback.xml] at [file:/Users/jaydez/Source/sqstest/target/classes/logback.xml]
00:25:00,567 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
00:25:00,576 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/Users/jaydez/Source/sqstest/target/classes/logback.xml]] every 60 seconds. 
00:25:00,576 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
00:25:00,581 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [myAppName]
00:25:00,581 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
00:25:00,585 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
00:25:00,611 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
00:25:00,673 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.eluder.logback.ext.sqs.appender.AsyncSqsAppender]
00:25:00,680 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SQS]
00:25:00,960 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@25:16 - RuntimeException in Action for tag [appender] java.lang.NullPointerException
	at java.lang.NullPointerException
	at 	at org.eluder.logback.ext.sqs.appender.SqsAppender.sqsInit(SqsAppender.java:95)
	at 	at org.eluder.logback.ext.sqs.appender.SqsAppender.start(SqsAppender.java:60)
	at 	at org.eluder.logback.ext.sqs.appender.AsyncSqsAppender.start(AsyncSqsAppender.java:62)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at 	at com.app.App.<clinit>(App.java:17)
	at 	at java.lang.Class.forName0(Native Method)
	at 	at java.lang.Class.forName(Class.java:264)
	at 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
00:25:00,960 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
00:25:00,960 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
00:25:00,960 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SQS] to Logger[ROOT]
00:25:00,960 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
00:25:00,962 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@9a7504c - Registering current configuration as safe fallback point
```

It appears to be something with the way Joran starts up the appender, passing it the context only after the appender is initialized. I've tried writing a fix, but I haven't been able to come up with an effective solution. Any ideas?

**Comment by jaydez** [comment]
@trautonen

**Comment by trautonen** [comment]
Sorry for late reply.

This appender is still very much work in progress and I have only tested manual programmatic configuration with it. I might have time to look at this in the next few days. I think one possible solution would be to create a delegate of ExecutorService that proxies the context until it is used for the first time. This way getting the context is delayed until the first log event is actually fired.

This is also my first logback experiment, so I have no idea how the configuration really works and what are the best practices of configuring and bootstrapping an appender. So any help is appreciated. :)

**Comment by trautonen** [comment]
Did some debugging and in fact for some reason appender is started before Joran sets the context. I created a new version with few fixes to initialization and shutdown. Now the SQS and SNS appenders are using lazy proxies of the executorservice.

You can try the new snapshot from Sonatype's repo.

**Comment by trautonen** [comment]
I've now tested bootstrapping the plugin from logback.xml configuration file with Joran configurer and it should work.

I also noticed that in your setup you are using encoder and layout. These are actually overlapping configurations. Layout is transformed into LayoutWrappingEncoder and overrides the Jackson encoder. You have basicly two choices how you want to encode the log messages.

Either use JSON encoder, which will eventually just translate all the attributes of the logging event into JSON format, and on the reading side you have to use your own formatter or just store the JSON in to a document database or whatever. The another way is to use for example pattern layout, which will format the message and pass the formatted message along (you lose all the structure and possibly the information that is not used in the pattern).

But you cannot use both, encoder and layout. Maybe I should throw an exception if layout is tried to set after encoder, or encoder is tried to set after layout.

**Comment by jaydez** [comment]
You've made some great improvements to the extension. And thanks for letting me know about the Layout/Encoder issue. In my testing of the bootstrapping I've found I'm still running into the 'No context given' problem I had encountered earlier.

    <configuration debug="true">
    <appender name="SQS" class="org.eluder.logback.ext.sqs.appender.AsyncSqsAppender">
        <accessKey>KEY</accessKey>
        <secretKey>KEY</secretKey>
        <queueUrl>URL</queueUrl>
        <encoder class="org.eluder.logback.ext.jackson.JacksonEncoder">
            <timeStampFormat>yyyy-MM-dd'T'HH:mm:ss</timeStampFormat>
        </encoder>
    </appender>

    <root level="DEBUG">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="SQS" />
    </root>
</configuration>

Here's the code I'm using to call it:

    package hey;
    import org.slf4j.Logger;
    import org.slf4j.LoggerFactory;
    public class App
    {
        static final Logger LOG = LoggerFactory.getLogger(App.class);
        public static void main( String[] args )
        {
            LOG.info("Hello log");
            System.out.println( "Hello World!" );
            LOG.info("Hello sqs");
        }
    }


How are you including your extension as a dependency? I find I need to include each individual component in my POM (using the Sonatype Snapshot repo).

    <dependency>
      <groupId>org.eluder.logback</groupId>
      <artifactId>logback-ext-sqs-appender</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.eluder.logback</groupId>
      <artifactId>logback-ext-jackson</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
and so on ...

And outputs this:

    10:10:31,594 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
    10:10:31,594 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
    10:10:31,594 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/jonathansmith/Source/sqstest2/target/classes/logback.xml]
    10:10:31,726 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
    10:10:31,728 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
    10:10:31,751 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
    10:10:31,790 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.eluder.logback.ext.sqs.appender.AsyncSqsAppender]
    LOGBACK: No context given for org.eluder.logback.ext.sqs.appender.AsyncSqsAppender[null]
    10:10:31,803 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SQS]
    10:10:32,343 |-INFO in org.eluder.logback.ext.sqs.appender.AsyncSqsAppender[SQS] - Setting discardingThreshold to 51
    10:10:32,343 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
    10:10:32,343 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
    10:10:32,343 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SQS] to Logger[ROOT]
    10:10:32,344 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
    10:10:32,345 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6f96c77 - Registering current configuration as safe fallback point
    10:10:32.347 default [main] INFO  hey.App - Hello log
    Hello World!
    10:10:32.349 default [main] INFO  hey.App - Hello sqs

But doesn't send anything to SQS. It could be an issue with my implementation since you've already confirmed that your code works.

**Comment by trautonen** [comment]
Is your application Dropwizard based? If so, this might be related: https://github.com/dropwizard/dropwizard/issues/734

If not, then back to square one... I did my test with simple unit test without any frameworks interfering the logback bootstrap. Just the XML configuration and logback dependencies along with the SQS and Jackson dependencies.

I think Joran should always attach the context unless there's some customization done for the SLF4J configuration. What frameworks or libraries you are using that might do something with SLF4J?

**Comment by jaydez** [comment]
That is the interesting part... I've successfully used it with the dropwizard framework, but when I try to run it standalone I encounter the error above.

The example I showed you comes from this repository: https://github.com/jaydez/sqstest

**Comment by trautonen** [comment]
Ah, the problem with your test app is that it exits immediately after logging some stuff. I couldn't figure what causes the no context problem, but most likely something is trying to add a status message for logback, just couldn't figure what. This does not affect the logging behavior of the appenders. If you add a small thread sleep in the end of your app you will see the messages in queue.

The next question is that is the daemon thread based logback managed executor service the right way to handle the async logging. I guess if other async loggers work the same way and you have a possibility to lose messages when the application is exiting, this is the desired way. Here's some related discussion about the async appenders: http://mailman.qos.ch/pipermail/logback-user/2014-March/004337.html

One solution would be to remove the internal async implementation of the SQS and SNS appenders and go for the sync api of AWS SDK. Then one could control the asyncness of the appender by using the asyncversion, which is totally controlled by logback, and possibly works as expected. Or at least someone else smarter has give a thought how it should work.

**Comment by jaydez** [comment]
Ah, that makes perfect sense. As for losing log messages when exiting, it seems to be the way things are working right now. You're doing some great work here, keep it up!

**Comment by SourabhaMandhana** [comment]
Hi,

I am unable to find the dependency as mentioned above. I have a use case to write Java application logs to SQS using Logback + SQS appender. ANy help is highly appreciated. Thank you in advance.

**Comment by unsiv** [comment]
https://www.mkyong.com/logging/how-to-stop-logback-status-info-at-the-start-of-every-log/ 

Its working fine for me
