### ISSUE TITLE
skipCreate logic reversed

### ISSUE THREAD

**Issue by treidel** [trautonen/logback-ext#3]
the logic for the skipCreate option is incorrect.  when skipCreate = true it skips the creation step.  

In the "doStart()" method in CloudWatchAppender.java: 

` if (skipCreate) {
            if (!logGroupExists(logGroup)) {
                createLogGroup(logGroup);
            }
            if (!logStreamExists(logGroup, logStream)) {
                createLogStream(logGroup, logStream);
            }
        }`

It should be:

`if (!skipCreate) {`

**Comment by trautonen** [comment]
Thanks for noticing this. Fixed and published to Sonatype snapshots.
