### ISSUE TITLE
Make it possible to add Encoder (to CW logger)

### ISSUE THREAD

**Issue by btd** [trautonen/logback-ext#5]
Hi.

This project looks pretty good, but it still need some work to make it usable in more common case. In Ch 4 of logback manual you can see that OutputStreamAppender uses Encoder interface to encode messages. It is right idea to add Encoder there also, instead of using your own always.

**Comment by trautonen** [comment]
You can already use custom encoders with all the appenders. The problem compared to normal logback appenders is that you cannot add a stream to any of the AWS endpoints, hence everything is encoded back to `String` which is then forwarded to AWS services in their specific format.

See the docs (unfinished) of CloudWatch appender for all configuration options.
https://github.com/trautonen/logback-ext/tree/master/logback-ext-cloudwatch-appender

For example you can configure the CloudWatch (or any other) appender like this to get nice JSON encoded output to CloudWatch. Or you can use the logback provided pattern encoder, or your own implemenatation.

```xml
    <appender name="cloudwatch" class="org.eluder.logback.ext.cloudwatch.appender.CloudWatchAppender">
        <accessKey>SDFDSFDSFDSFFDS</accessKey>
        <secretKey>sfdskjkdsfSDFsadfsfddsfds</secretKey>
        <region>eu-west-1</region>
        <logGroup>myloggroup</logGroup>
        <logStream>mylogstream</logStream>
        <encoder class="org.eluder.logback.ext.jackson.JacksonEncoder">
            <timeStampFormat>yyyy-MM-dd'T'HH:mm:ss.SSSZZZ</timeStampFormat>
        </encoder>
    </appender>
```

**Comment by btd** [comment]
Thanks, it is what i am looking for. It looks i miss somewhere setEncoder.

**Comment by trautonen** [comment]
It is hidden pretty far in the hierarchy:
https://github.com/trautonen/logback-ext/blob/master/logback-ext-core/src/main/java/org/eluder/logback/ext/core/EncodingStringAppender.java

That does all the encoding magic. And the name is a bit misleading (should refactor to something more describing). I first had an implementation that took the bytes from the encoder and converted it always back to `String`, but it wasn't useful in all cases, so now it is actually generic and does the event encoding in two parts.

1. encodes the event with the defined encoder
2. converts the bytes from a single logging event to the type what the payload converter defines (this is mostly `String`, but can be any type)
